name = "wolfbin-worker"
main = "worker.js"
compatibility_date = "2025-10-20"

# Bind your Workers KV namespace
[env.production]
kv_namespaces = [
  { binding = "WOLFBIN", id = "REPLACE_WITH_KV_NAMESPACE_ID" }
]